"""Add fsrs_data JSONB column to review_logs

Revision ID: a777489ed07f
Revises: a7b6c625f10d
Create Date: 2025-10-14 19:39:02.082474+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a777489ed07f'
down_revision: Union[str, None] = 'a7b6c625f10d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card_progress', 'fsrs_state',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('idx_card_progress_next_review'), table_name='card_progress')
    op.drop_index(op.f('idx_cards_level'), table_name='cards')
    op.drop_constraint(op.f('profiles_user_id_fkey'), 'profiles', type_='foreignkey')
    op.add_column('review_logs', sa.Column('fsrs_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('idx_review_logs_user_created'), table_name='review_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_review_logs_user_created'), 'review_logs', ['user_id', sa.literal_column('reviewed_at DESC')], unique=False)
    op.drop_column('review_logs', 'fsrs_data')
    op.create_foreign_key(op.f('profiles_user_id_fkey'), 'profiles', 'users', ['id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.create_index(op.f('idx_cards_level'), 'cards', ['level_id'], unique=False)
    op.create_index(op.f('idx_card_progress_next_review'), 'card_progress', ['user_id', 'next_review'], unique=False)
    op.alter_column('card_progress', 'fsrs_state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
